App/home/forms.py
# -*- coding: utf-8 -*
# @Time    : 2022/2/10 15:06
# @Author  : liuy
# @File    : forms.py


from flask_wtf import FlaskForm
from wtforms.fields import StringField, PasswordField, SubmitField, FileField, TextAreaField, EmailField
from wtforms.validators import DataRequired, EqualTo, Email, Regexp, ValidationError
from App.models import User

# 登录表单
class LoginForm(FlaskForm):
    name = StringField(
        label="账号",
        validators=[
            DataRequired("请输入帐号！")    # 这个字段不能为空
        ],
        description="账号",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入帐号！"
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！",
        }
    )
    submit = SubmitField(
        "登录",
        render_kw={
            "class": "btn btn-lg btn-primary btn-block"
        }
    )

    def validate_name(self, field):
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user == 0:
            raise ValidationError("会员账号不存在！")

    def validata_pwd(self, field):
        pwd = field.data
        name = self.name.data
        user = User.query.filter_by(name=name).count()
        if not user.check_pwd(pwd):
            raise ValidationError("密码错误！")


# 注册表单
class RegistForm(FlaskForm):
    name = StringField(
        label="呢称",
        validators=[
            DataRequired("请输入呢称！")
        ],
        description="呢称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入呢称！",
        }
    )
    email = EmailField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱！"),
            # Email("邮箱格式不正确！"),
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱！"
        }
    )
    phone = StringField(
        label="手机号",
        validators=[
            DataRequired("请输入手机号！"),
            Regexp("1[34578]\\d{9}", message="输入的手机号格式不正确！"),
        ],
        description="手机号",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入手机号！"
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码！"
        }
    )
    repwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请输入确认密码！"),
            EqualTo("pwd", message="两次密码不一致！")
        ],
        description="确认密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入确认密码！"
        }
    )
    submit = SubmitField(
        "注册",
        render_kw={
            "class": "btn btn-lg btn-success btn-block"
        }
    )

    def validate_name(self, field):               # 这是一个钩子函数  对用户名进行验证
        name = field.data                         # field.data 就是当前name从表单提交过来的值
        user = User.query.filter_by(name=name).count()   # 从数据库里面取值
        if user == 1:                             # 如果从数据库里取到了这个值。说明用户名存在
            raise ValidationError("呢称已经存在，请重新输入！")

    def validate_email(self, field):
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError("邮箱已经存在，请重新输入！")

    def validate_phone(self, field):
        phone = field.data
        user = User.query.filter_by(phone=phone).count()
        if user == 1:
            raise ValidationError("手机号已经存在，请重新输入！")


# 用户表
class UserdetailForm(FlaskForm):
    name = StringField(
        label="呢称",
        validators=[
            DataRequired("请输入呢称！")
        ],
        description="呢称",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入呢称！"
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱！"),
            # Email("邮箱的格式不正确，请重新输入！")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入邮箱！"
        }
    )
    phone = StringField(
        label="手机号",
        validators=[
            DataRequired("请输入手机号！"),
            Regexp("1[34578]\\d{9}", message="输入的手机号格式不正确！"),
        ],
        description="手机号",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入手机号！"
        }
    )
    face = FileField(
        label="头像",
        validators=[
            DataRequired("请上传头像！")
        ],
        description="头像"
    )
    info = TextAreaField(
        label="简介",
        validators=[
            DataRequired("请输入简介！")
        ],
        description="简介",
        render_kw={
            "class": "form-control",
            "rows": "10"
        }
    )
    submit = SubmitField(
        "保存修改",
        render_kw={
            "class": "btn btn-success",
        }
    )


class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label="旧密码",
        validators=[
            DataRequired("请输入旧密码!")
        ],
        description="旧密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入旧密码!"
        }
    ),
    new_pwd = PasswordField(
        label="新密码",
        validators=[
            DataRequired("请输入新密码!")
        ],
        description="新密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入新密码!"
        }
    )
    submit = SubmitField(
        "修改密码",
        render_kw={
            "class": "btn btn-success"
        }
    )


# 评论表单
class CommentForm(FlaskForm):
    content = TextAreaField(
        label="内容",
        validators=[
            DataRequired("请输入内容！"),
        ],
        description="内容",
        render_kw={
            "id": "input_content",
            "class": "form-control",
            "rows": "10"
        }
    )
    submit = SubmitField(
        label='提交评论',
        render_kw={
            "class": "btn btn-success",
            "id": "btn-sub"
        }
    )

App/home/__init__.py
# -*- coding: utf-8 -*
# @Time    : 2022/2/10 15:04
# @Author  : liuy
# @File    : __init__.py

from flask import Blueprint

home = Blueprint("home", __name__)

import App.home.views

App/home/views.py
# -*- coding: utf-8 -*
# @Time    : 2022/2/10 15:05
# @Author  : liuy
# @File    : views.py
import os
import uuid
from functools import wraps

from flask import render_template, redirect, url_for, session, flash, request, Flask
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from .forms import LoginForm, RegistForm, UserdetailForm, PwdForm, CommentForm
from App.models import db, Comment, Moviecol, Preview
from ..admin.views import change_filename
from ..models import User, Userlog, Tag, Movie
from . import home


# 定义装饰器，必须登录后才能访问
def user_login_req(func):
    @wraps(func)
    def decorated_function(*args, **kwargs):
        if session.get('home', None) is None:
            return redirect(url_for('home.play', id=1, page=1))
        return func(*args, **kwargs)
    return decorated_function


@home.route("/login/", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():     # 如果用户输入的用户名和密码符合验证条件
        data = form.data              # 获取用户输入的表单数据
        user = User.query.filter_by(name=data.get("name")).first()      # 根据用户名查询数据库，返回第一个查询结果
        if user == None:              # 如果从数据库中查不到用户名
            flash("会员账号不存在,请重新输入！", "err")
            return redirect(url_for("home.login"))
        elif not user.check_pwd(data.get("pwd")):         # 如果从数据库查询到用户名但密码不匹配
            flash("用户名或密码错误！", "err")
            return redirect(url_for("home.login"))
        session['user'] = user.name             # 定义session信息
        session['user_id'] = user.id
        userlog = Userlog(                     # 定义用户登录日志
            user_id=user.id,
            ip=request.remote_addr
        )
        db.session.add(userlog)                 # 添加用户登录日志
        db.session.commit()
        return redirect(url_for("home.user"))
    return render_template("home/login.html", form=form)


@home.route("/logout/")
def logout():
    session.pop("user", None)            # 从session中删除用户名
    session.pop("user_id", None)         # 从session中删除用户id
    return redirect(url_for("home.login"))


@home.route("/register/", methods=["GET", "POST"])
def register():
    form = RegistForm()                    # 获取用户输入的注册信息数据
    if form.validate_on_submit():          # 如果用户输入的注册数据通过form基础验证
        data = form.data                   # 获取用户输入的表单数据
        user = User(
            name=data.get("name"),        # 从表单中获取用户输入的用户名
            email=data.get("email"),      # 从表单中获取用户输入的邮箱地址
            phone=data.get("phone"),      # 从表单中获取用户输入的手机号
            pwd=generate_password_hash(data.get("pwd")),          # 从表单中获取用户输入的密码并进行加密
            uuid=uuid.uuid4().hex         # 生成uuid,保证唯一性
        )
        db.session.add(user)             # 添加用户
        db.session.commit()              # 向数据库提交用户注册信息
        flash("注册成功！", "ok")
        return redirect(url_for("home.login"))
    return render_template("home/register.html", form=form)


@home.route("/<int:page>/", methods=['GET'])
@home.route("/", methods=['GET'])
def index(page=None):
    tags = Tag.query.all()              # 获取数据库中所有的电影标签
    page_data = Movie.query             # 从数据库中获取所有的电影信息    page_data就是电影对象

    tid = request.args.get("tid", 0)    # 获取用户请求的电影标签id
    if int(tid) != 0:
        page_data = page_data.filter_by(tag_id=int(tid))    # 根据用户请求的页码进行过滤

    star = request.args.get("star", 0)    # 获取用户请求的电影星级id
    if int(star) != 0:
        page_data = page_data.filter_by(star=int(star))    # 根据用户请求的电影星级id进行过滤

    time = request.args.get("time", 0)    # 获取用户请求的电影添加时间
    if int(time) != 0:
        page_data = page_data.order_by(Movie.addtime)    # 获取用户请求的电影添加时间进行过滤

    pm = request.args.get("pm", 0)    # 获取用户请求的电影播放次数
    if int(pm) != 0:
        page_data = page_data.order_by(Movie.playnum)    # 获取用户请求的电影播放次数进行过滤

    cm = request.args.get("cm", 0)    # 获取用户请求的电影评论次数
    if int(cm) != 0:
        page_data = page_data.order_by(Movie.commentnum)    # 获取用户请求的电影评论次数进行过滤

    if page is None:    # 获取用户请求的页数
        page = 1
    page_data = page_data.paginate(page=page, per_page=10)    # 进行分页，每页显示10条电影数据

    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )    # 定义返回给前端页面的字典信息
    return render_template("home/index.html", tags=tags, p=p, page_data=page_data)


# 会员详情
@home.route("/user/", methods=['GET', 'POST'])
def user():
    if session.get("user_id") is None:
        form = LoginForm()
        return render_template("home/login.html", form=form)
    else:
        form = UserdetailForm()
        user = User.query.get(int(session.get("user_id")))
        form.face.validators = []
        if request.method == 'GET':
            form.name.data = user.name
            form.email.data = user.email
            form.phone.data = user.phone
            form.info.data = user.info

        if form.validate_on_submit():
            data = form.data
            # 验证头像是否存在
            path = "App/static/uploads/users/"
            file_face = secure_filename(form.face.data.filename)
            if not os.path.exists(path):     # 判断括号里的文件是否存在，括号内的可以是文件路径。
                os.makedirs(path)            # 递归创建目录
                os.chmod(path)         # 修改目录权限
            user.face = change_filename(file_face)           # 修改文件名称
            form.face.data.save(path + user.face)
            # 验证用户名是否存在
            name_count = User.query.filter_by(name=data.get("name")).count()
            if data.get("name") != user.name and name_count == 1:
                flash("用户名已经存在,请重新输入！", "err")
                return redirect(url_for("home.user"))
            # 验证邮箱是否存在
            email_count = User.query.filter_by(email=data.get("email")).count()
            if data.get("email") != user.email and email_count == 1:
                flash("邮箱已经存在，请重新输入！", "err")
                return redirect(url_for("home.user"))
            # 验证手机号是否存在
            phone_count = User.query.filter_by(phone=data.get('phone')).count()
            if data.get("phone") != user.phone and phone_count == 1:
                flash("手机号已经存在，请重新输入！", "err")
                return redirect(url_for("home.user"))
            user = User(
                name=data.get("name"),
                email=data.get("email"),
                phone=data.get("phone"),
                info=data.get("info"),
            )
            db.session.add(user)
            db.session.commit()
            flash("修改已经保存！", "ok")
            return redirect(url_for("home.user"))
        return render_template("home/user.html", form=form, user=user)


@home.route("/pwd/", methods=['GET', 'POST'])
def pwd():
    form = PwdForm()
    print(form.data)
    if form.validate_on_submit():
        data = form.data
        print(data)
        user = User.query.filter_by(name=session.get("user")).first()
        if not user.check_pwd(data.get("pwd")):
            flash("旧密码输入错误，请重新输入！", "err")
            return redirect(url_for("home.pwd"))

        from werkzeug.security import generate_password_hash
        user.pwd = generate_password_hash(data.get("new_pwd"))
        db.session.add(user)
        db.session.commit()
        flash("修改密码成功，请重新登录！", "ok")
        return redirect(url_for("home.logout"))
    return render_template("home/pwd.html", form=form)


# 用户评论
@home.route("/comments/<int:page>/")
def comments(page=None):
    if page is None:
        page = 1
    page_data = Comment.query.join(Movie).join(User).filter(
        Movie.id == Comment.movie_id,
        User.id == session["user_id"]
    ).order_by(Comment.id).paginate(page=page, per_page=10)
    return render_template("home/comments.html", page_data=page_data)


@home.route("/loginlog/<int:page>/", methods=['GET'])
def loginlog(page=None):
    if page is None:
        page = 1
    page_data = Userlog.query.filter_by(user_id=int(session.get("user_id"))).order_by(
        Userlog.id).paginate(page=page, per_page=10)

    return render_template("home/loginlog.html", page_data=page_data)


# 电影收藏表
@home.route("/moviecol/<int:page>/")
def moviecol(page=None):
    if page is None:
        page = 1
    page_data = Moviecol.query.join(Movie).join(User).filter(
        Movie.id == Moviecol.movie_id,
        User.id == session.get("user_id")
    ).order_by(Moviecol.id).paginate(page=page, per_page=10)
    return render_template("home/moviecol.html", page_data=page_data)


# 搜索页面
@home.route('/search/', methods=['post','get'])
def search(page=None):
    if page is None:
        page = 1
    keyword = request.args.get("keyword", "")
    movie_count = Movie.query.filter(
        Movie.title.ilike('%' + keyword + '%')
    ).count()
    page_data = Movie.query.filter(
        Movie.title.ilike('%' + keyword + '%')
    ).order_by(
        Movie.addtime.desc()
    ).paginate(page=page, per_page=10)
    page_data.key = keyword
    return render_template("home/search.html", movie_count=movie_count, keyword=keyword, page_data=page_data)


# 首页轮播图页面
@home.route('/animation/')
def animation():
    data = Preview.query.all()
    for v in data:
        v.id = v.id - 1
    return render_template("home/animation.html", data=data)


# 电影
@home.route('/play/<int:id>/<int:page>/', methods=["GET", "POST"])
def play(id=None, page=None):
    # 查询出相关联的标签
    movie = Movie.query.join(Tag).filter(
        Tag.id == Movie.tag_id,
        Movie.id == int(id)
    ).first_or_404()

    if page is None:
        page = 1
    page_data = Comment.query.join(Movie).join(User).filter(
        Movie.id == movie.id,
        User.id == Comment.user_id
    ).order_by(Comment.addtime.desc()).paginate(page=page, per_page=10)
    form = CommentForm()
    # 必须登录才能评论  session中的值是该用户的名字
    name = session.get("user")
    user = User.query.filter_by(name=name).first()
    if form.validate_on_submit() and 'user' in session:
        data = form.data
        comment = Comment(
            content=data["content"],
            movie_id=movie.id,
            user_id=session["user_id"]
        )
        db.session.add(comment)

App/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/animate.css') }}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
</head>

{% block css %}

{% endblock %}

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index',page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',filename='base/images/logo.png') }}" style="height:30px;">&nbsp;电影天堂
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="keyword" value="{{ keyword }}">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index') }}"><span
                            class="glyphicon glyphicon-film"></span>&nbsp;首页</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span
                            class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span
                            class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span
                            class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->
    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}

    {% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2022&nbsp;flaskmovie.com&nbsp;电影天堂
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    })
</script>
<script>
    $(document).ready(function () {
        $("#do_search").click(function () {
            let keyword = $('#keyword').val();
            location.href = "{{ url_for('home.search') }}?keyword=" + keyword;
        });
    })
</script>

{% block js %}

{% endblock %}

</body>
</html>

App/templates/home/index.html
{% extends "home/home.html" %}
{% import "ui/home_page.html" as pg %}

{% block content %}
    <!--热门电影-->
    <section id="hotmovie" style="margin-top:76px">
        <div class="container">
            <div class="row wow fadeInRight" data-wow-delay="0.6s">
                <div class="row">
                    <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no
                            src="{{ url_for('home.animation') }}"></iframe>
                </div>
            </div>
        </div>
    </section>
    <!--热门电影-->
    <!--电影列表筛选条件-->
    <section id="movielist">
        <div class="container">
            <div class="row wow fadeIn" data-wow-delay="0.6s">
                <div class="col-md-12 table-responsive">
                    <table class="table text-left table-bordered" id="movietags">
                        <tr>
                            <td style="width:10%;">电影标签</td>
                            <td style="width:90%;">
                                {% for v in tags %}
                                    <a href="{{ url_for('home.index',page=1) }}?tid={{ v.id }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                                       class="label label-info"><span
                                            class="glyphicon glyphicon-tag"></span>&nbsp;{{ v.name }}</a>
                                    &nbsp;
                                {% endfor %}
                        </tr>
                        <tr>
                            <td>电影星级</td>
                            <td>
                                {% for v in range(1,6) %}
                                    <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ v }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                                       class="label label-warning"><span
                                            class="glyphicon glyphicon-star"></span>&nbsp;{{ v }}星</a>
                                    &nbsp;
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <td>上映时间</td>
                            <td>
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=1&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                                   class="label label-default"><span
                                        class="glyphicon glyphicon-time"></span>&nbsp;最近
                                </a>
                                &nbsp;
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=2&pm={{ p['pm'] }}&cm={{ p['cm'] }}"
                                   class="label label-default"><span
                                        class="glyphicon glyphicon-time"></span>&nbsp;更早
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>播放数量</td>
                            <td>
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=1&cm={{ p['cm'] }}"
                                   class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</a>
                                &nbsp;
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=2&cm={{ p['cm'] }}"
                                   class="label label-danger"><span
                                        class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</a>
                            </td>
                        </tr>
                        <tr>
                            <td>评论数量</td>
                            <td>
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=1"
                                   class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</a>
                                &nbsp;
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=2"
                                   class="label label-danger"><span
                                        class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</a>
                            </td>
                        </tr>
                    </table>
                </div>
                {% for v in page_data.items %}
                    <div class="col-md-3">
                        <div class="movielist text-center">
                            <!--<img data-original="holder.js/262x166"
                                     class="img-responsive lazy center-block" alt="">-->
                            <img src="{{ url_for('static',filename='video/logo/'+v.logo) }}"
                                 class="img-responsive center-block"
                                 alt="">
                            <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                                <span style="color:#999;font-style: italic;">{{ v.title }}</span><br>
                                <div>
                                    {% for val in range(1,v.star+ 1) %}
                                        <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                                    {% endfor %}
                                    {% for val in range(1,5-v.star+ 1) %}
                                        <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                                    {% endfor %}
                                </div>
                            </div>
                            <a href="{{ url_for('home.play',id=v.id, page=1) }}" class="btn btn-primary" target="_blank"
                               role="button"><span class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                        </div>
                    </div>
                {% endfor %}

                <div class="col-md-12">
                    {{ pg.page(page_data,'home.index') }}
                </div>
            </div>
        </div>
    </section>
    <!--电影列表-->
{% endblock %}

App/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id='m-1' href="{{ url_for('home.user') }}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
        <a id='m-2' href="{{ url_for('home.pwd') }}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id='m-3' href="{{ url_for('home.comments',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id='m-4' href="{{ url_for('home.loginlog',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id='m-5' href="{{ url_for('home.moviecol',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>

App/templates/home/moviecol_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>add</p>
</body>
</html>